### ISSUE TITLE
Feature request: section for shuffle (random) post

### ISSUE THREAD

**Issue by gojigeje** [gilankpam/wancak#1]
API nya keren gan, gak sengaja nemu dari google. kebetulan juga lagi bikin script parser judul dan gambar post 1cak, tapi dari bash dan banyak kendala.
Kalau boleh minta tolong tambahin fitur tambahi section buat kategori shuffle/random (http://1cak.com/shuffle), dan API ini bakal lebih keren.. :smile:

**Comment by gilankpam** [comment]
Done!
Added new feature: random, single post

Thanks for your feedback :)

**Comment by gojigeje** [comment]
Tested and works perfectly.. :+1: 
I have another challenge for you gan.. another feature request, will open new issue after this..
