### ISSUE TITLE
Feature request: search post using specific keyword

### ISSUE THREAD

**Issue by gojigeje** [gilankpam/wancak#2]
Another feature request, gan!
Search post using specific keyword:
http://1cak.com/search-0-jomblo <-- keyword is "jomblo"
http://1cak.com/search-0-jomblo%20ngenes <-- keyword is "jomblo ngenes"

should be easy for you, gan :smile:
sorry I'm still unable to contribute some code, didn't have any golang experience..

**Comment by gilankpam** [comment]
feature added

sorry lama, baru sempet huhuhu

**Comment by gojigeje** [comment]
nice gan!

tapi ane masih kurang faham gimana implementasi parameter pageid di search.
ane coba isi `&pageid=1` atau `&pageid=2` malah eror:

```
{"message":"Posts not found","status":"error"}
```

**Comment by gilankpam** [comment]
page idnya dapet dari response sebelumnya

```
{  
    "page":{  
        "next":"1424046302"
    },
```

**Comment by gojigeje** [comment]
ah.. ane yang kurang teliti..
sipp.. perfect nih gan :+1:
