### ISSUE TITLE
Q: is it possible to have more than 3 posts on per-section request?

### ISSUE THREAD

**Issue by gojigeje** [gilankpam/wancak#3]
I know right now the API displays 3 posts per request because that is how 1cak website designed (only display 3 posts per page, another posts is loaded via ajax) and what this API doing is parsing html code from 1cak website (cmiiw), but this is not something that impossible, right?

Saya masih pelajari kodenya agan (baru 2 hari belajar go), semoga lekas dapat pencerahan dan bisa koding go juga :smile:

**Comment by gilankpam** [comment]
yes, it is possible, but the server have to make more than one request, which is not what i want :p 

semangat gan :D

**Comment by gojigeje** [comment]
so i'm assuming that you wont add this feature on your code, right?
sayang ya harus terbatasi dari website 1cak nya.. ane close kl gitu..
